stages:
  - pre_release # a single stage allows test to run even if flake8 fails and makes it possible to get all the errors at once
  - release
  - deploy

flake8:
  extends:
    - .except_nightly_test
  tags:
    - docker
  image: python:3
  stage: pre_release
  script:
    - pip install black flake8 flake8-black pep8-naming flake8-bugbear --constraint requirements-dev.txt
    - flake8 -v mixer tests extra


doc:
  stage: pre_release
  extends:
    - .except_on_gitlab.com
    - .except_nightly_test
  tags:
    - docker
  image: python:3
  when: manual
  script:
    - pip install sphinx sphinx-rtd-theme
    - sphinx-build -b html docs docs/_build/html
    - rm -rf docs/_build/doctree
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_html"
    paths:
      - docs/_build
    expire_in: 1 week

zip:
  extends:
    - .except_nightly_test
  tags:
    - docker
  image: alpine
  stage: pre_release
  script:
    - cp CHANGELOG.md README.md LICENSE mixer/
    - rm -rf mixer/blender_data/tests/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - mixer
    expire_in: 1 week

# Note: you cannot extend this job with another only: variables job
# If you need that, you should rewrite and combine the rules
.only_on_gitlab.com:
  only:
    variables:
      - $CI_SERVER_URL == "https://gitlab.com"

# Note: you cannot extend this job with another except: variables job
# If you need that, you should rewrite and combine the rules
.except_on_gitlab.com:
  except:
    variables:
      - $CI_SERVER_URL == "https://gitlab.com"

# Note: you cannot extend this job with another only: variables job
# If you need that, you should rewrite and combine the rules
.only_version_tag:
  only:
    refs:
      # see inject_version.py
      - /^v([0-9]+)\.([0-9]+)\.([0-9]+)(\-[0-9A-Za-z-]+)?(\+[0-9A-Za-z-]+)?$/

.except_nightly_test:
  except:
    variables:
      - $NIGHTLY_TEST == "true"

.only_nightly_test:
  only:
    variables:
      - $NIGHTLY_TEST == "true"

release:
  extends:
    - .only_version_tag
    - .except_nightly_test
  dependencies:
    - zip
  tags:
    - docker
  image: python:3
  stage: release
  script:
    - pip install requests
    - python -m zipfile -c mixer-${CI_COMMIT_REF_NAME}.zip mixer/
    - python -m gitlab.release mixer-${CI_COMMIT_REF_NAME}.zip
  artifacts:
    paths:
      - mixer-${CI_COMMIT_REF_NAME}.zip

####################################################################################

# https://gitlab-ncsa.ubisoft.org/help/ci/yaml/README.md


.test_base:
  stage: pre_release
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip-tests\]/
  tags:
    - blender
  variables:
    MIXER_BASH_EXE: C:\Program Files\Git\bin\bash.exe
    VRTIST_PORT: 25600 # In case a server is already running on our default port on the test computer
    MIXER_TEST_OUTPUT: logs\tests
  timeout: 2h
  script:
    - gitlab\run_unittest.bat
  cache:
    paths:
      - gitlab/blender/cache
  artifacts:
    paths:
      - logs\tests\*.xml
    reports:
      junit:
        - logs\tests\*.xml


.test_nightly:
  extends:
    - .test_base
    - .except_on_gitlab.com
    - .only_nightly_test


.test_dev_version:
  variables:
    MIXER_BLENDER_ZIP_BASENAME: blender-2.91.0-windows64
    MIXER_BLENDER_VERSION_BASE: "2.91"
    MIXER_BLENDER_DOWNLOAD: "release"

test_dev:
  extends:
    - .test_base
    - .test_dev_version
    - .except_nightly_test

test_2.91.2:
  extends:
    - .test_nightly
  variables:
    MIXER_BLENDER_VERSION_BASE: "2.91"
    MIXER_BLENDER_ZIP_BASENAME: blender-2.91.2-windows64
    MIXER_BLENDER_DOWNLOAD: "release"

test_2.92.beta:
  extends:
    - .test_nightly
  variables:
    MIXER_BLENDER_VERSION_BASE: "2.92"
    # from https://builder.blender.org/download/
    MIXER_BLENDER_ZIP_BASENAME: blender-2.92.${beta}-windows64
    MIXER_BLENDER_DOWNLOAD: "builder"

test_2.93.alpha:
  extends:
    - .test_nightly
  variables:
    MIXER_BLENDER_VERSION_BASE: "2.93"
    # from https://builder.blender.org/download/
    MIXER_BLENDER_ZIP_BASENAME: blender-2.93.${alpha}-windows64
    MIXER_BLENDER_DOWNLOAD: "builder"

test_gitlab.com:
  extends:
    - .test_base
    - .test_dev_version
    - .only_version_tag
    - .only_on_gitlab.com

#########################################################################################

.deploy_network_folder:
  stage: deploy
  extends:
    - .only_version_tag
    - .except_on_gitlab.com
    - .except_nightly_test
  tags:
    - linux
    - uas_network_drive
  script:
    - bash gitlab/deploy_in_network_folder.sh mixer-${CI_COMMIT_REF_NAME}.zip
  when: manual

.deploy_perforce_folder:
  stage: deploy
  extends:
    - .only_version_tag
    - .except_on_gitlab.com
    - .except_nightly_test
  tags:
    - linux
    - uas_perforce_client
  script:
    - bash gitlab/deploy_in_perforce_folder.sh mixer-${CI_COMMIT_REF_NAME}.zip
  when: manual

deploy:incubator:
  extends: .deploy_network_folder
  environment:
    name: incubator

deploy:rr_special:
  extends: .deploy_perforce_folder
  environment:
    name: rr_special
